[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "gnumake", "pkg-config", "sqlite"]

[phases.install]
cmds = ["cd server && npm install && npm rebuild sqlite3", "cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && npm rebuild sqlite3 && node server.js"
